## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv(r"C:\Users\Manuel\OneDrive - Grupo Empresarial Turbamex SA de CV\Documents\GitHub\world_weather_analysis\Weather_Database\WeatherPy_Database.csv")
city_data_df

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dong Hoi,VN,17.4833,106.6000,78.04,88,100,6.35,overcast clouds
1,1,Carnarvon,AU,-24.8667,113.6333,70.79,60,100,5.59,overcast clouds
2,2,Qaanaaq,GL,77.4840,-69.3632,19.20,85,45,5.37,scattered clouds
3,3,Moses Lake,US,47.1301,-119.2781,72.88,38,75,7.47,broken clouds
4,4,Mimongo,GA,-1.6195,11.6068,69.08,98,91,2.55,light rain
...,...,...,...,...,...,...,...,...,...,...
708,708,Cananeia,BR,-25.0147,-47.9267,65.86,86,0,4.61,clear sky
709,709,Krasnoselkup,RU,65.7000,82.4667,38.43,79,0,8.66,clear sky
710,710,Hailar,CN,49.2000,119.7000,58.15,36,100,1.19,overcast clouds
711,711,Zaria,NG,11.1113,7.7227,79.99,44,8,6.49,clear sky
712,712,Ippy,CF,6.2679,21.2247,70.23,87,66,2.39,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dong Hoi,VN,17.4833,106.6000,78.04,88,100,6.35,overcast clouds
5,5,Faanui,PF,-16.4833,-151.7500,80.67,65,6,11.97,clear sky
6,6,Albany,US,42.6001,-73.9662,75.78,46,99,5.53,overcast clouds
9,9,Hithadhoo,MV,-0.6000,73.0833,83.05,66,100,4.81,overcast clouds
13,13,Rincon,US,32.2960,-81.2354,85.86,73,27,11.18,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
683,683,Kedougou,SN,12.5579,-12.1743,86.79,50,100,1.30,overcast clouds
690,690,Kuching,MY,1.5500,110.3333,77.22,94,20,0.00,heavy intensity rain
704,704,Nyaunglebin,MM,17.9500,96.7333,75.33,94,99,3.80,overcast clouds
706,706,Gusau,NG,12.1628,6.6614,87.89,31,11,4.92,few clouds
711,711,Zaria,NG,11.1113,7.7227,79.99,44,8,6.49,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City ID                205
City                   205
Country                205
Lat                    205
Lng                    205
Max Temp               205
Humidity               205
Cloudiness             205
Wind Speed             205
Current Description    205
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dong Hoi,VN,17.4833,106.6000,78.04,88,100,6.35,overcast clouds
5,5,Faanui,PF,-16.4833,-151.7500,80.67,65,6,11.97,clear sky
6,6,Albany,US,42.6001,-73.9662,75.78,46,99,5.53,overcast clouds
9,9,Hithadhoo,MV,-0.6000,73.0833,83.05,66,100,4.81,overcast clouds
13,13,Rincon,US,32.2960,-81.2354,85.86,73,27,11.18,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
683,683,Kedougou,SN,12.5579,-12.1743,86.79,50,100,1.30,overcast clouds
690,690,Kuching,MY,1.5500,110.3333,77.22,94,20,0.00,heavy intensity rain
704,704,Nyaunglebin,MM,17.9500,96.7333,75.33,94,99,3.80,overcast clouds
706,706,Gusau,NG,12.1628,6.6614,87.89,31,11,4.92,few clouds
711,711,Zaria,NG,11.1113,7.7227,79.99,44,8,6.49,clear sky

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Dong Hoi,VN,78.04,overcast clouds,17.4833,106.6000,
5,Faanui,PF,80.67,clear sky,-16.4833,-151.7500,
6,Albany,US,75.78,overcast clouds,42.6001,-73.9662,
9,Hithadhoo,MV,83.05,overcast clouds,-0.6000,73.0833,
13,Rincon,US,85.86,scattered clouds,32.2960,-81.2354,
...,...,...,...,...,...,...,...
683,Kedougou,SN,86.79,overcast clouds,12.5579,-12.1743,
690,Kuching,MY,77.22,heavy intensity rain,1.5500,110.3333,
704,Nyaunglebin,MM,75.33,overcast clouds,17.9500,96.7333,
706,Gusau,NG,87.89,few clouds,12.1628,6.6614,
711,Zaria,NG,79.99,clear sky,11.1113,7.7227,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat}, {lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping.")

Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.
Hotel not found...skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df = hotel_df[hotel_df['Hotel Name'] != '']
clean_hotel_df = hotel_df
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Dong Hoi,VN,78.04,overcast clouds,17.4833,106.6000,Nam Long Hotel
5,Faanui,PF,80.67,clear sky,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
9,Hithadhoo,MV,83.05,overcast clouds,-0.6000,73.0833,Scoop Guest House
13,Rincon,US,85.86,scattered clouds,32.2960,-81.2354,Days Inn Rincon
15,Puerto Ayora,EC,75.16,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
...,...,...,...,...,...,...,...
683,Kedougou,SN,86.79,overcast clouds,12.5579,-12.1743,Relais de KÃ©dougou
690,Kuching,MY,77.22,heavy intensity rain,1.5500,110.3333,Hilton Kuching
704,Nyaunglebin,MM,75.33,overcast clouds,17.9500,96.7333,Thi ha
706,Gusau,NG,87.89,few clouds,12.1628,6.6614,GUEST INN
711,Zaria,NG,79.99,clear sky,11.1113,7.7227,A.B.U Hotels

In [10]:
# 8a. Create the output File (CSV)
output_data_file = (r"C:\Users\Manuel\OneDrive - Grupo Empresarial Turbamex SA de CV\Documents\GitHub\world_weather_analysis\Vacation_Search\WeatherPy_vacation.csv")

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))